/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as common from "./common";
export type { common };
import type * as interface from "./interface";
export type { interface };
import type * as test from "./test";
export type { test };
export type { CrossChainBridgeV2 } from "./CrossChainBridgeV2";
export type { CrossChainControl } from "./CrossChainControl";
