/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICrossChainFunctionCall,
  ICrossChainFunctionCallInterface,
} from "../../../contracts/interface/ICrossChainFunctionCall";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_bcId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_functionCallData",
        type: "bytes",
      },
    ],
    name: "crossBlockchainCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICrossChainFunctionCall__factory {
  static readonly abi = _abi;
  static createInterface(): ICrossChainFunctionCallInterface {
    return new Interface(_abi) as ICrossChainFunctionCallInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICrossChainFunctionCall {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICrossChainFunctionCall;
  }
}
