/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICrossChainFunctionCall__factory } from "./ICrossChainFunctionCall__factory";
export { ICrossChainVerifier__factory } from "./ICrossChainVerifier__factory";
