/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICrossChainFunctionCall } from "./ICrossChainFunctionCall";
export type { ICrossChainVerifier } from "./ICrossChainVerifier";
