/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HiddenParamDestTest__factory } from "./HiddenParamDestTest__factory";
export { HiddenParamSourceTest__factory } from "./HiddenParamSourceTest__factory";
